mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from mysite import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('<int:pk>/profile', views.Profile.as_view(), name='profile'),
    path('<int:pk>/delete_user', views.DeleteUser.as_view(), name='delete_user'),
    path('<int:pk>/update_user', views.UpdateUser.as_view(), name='update_user'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    first_name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    last_name = models.CharField(max_length=254, verbose_name='Фамилия', blank=False)
    username = models.CharField(max_length=254, verbose_name='Логин', unique=True, blank=False)
    email = models.CharField(max_length=254, verbose_name='Почта', unique=True, blank=False)
    password = models.CharField(max_length=254, verbose_name='Пароль', blank=False)
    avatar = models.ImageField(upload_to='polls/user', verbose_name='Аватарка', blank=False)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.first_name


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    short_description = models.CharField(max_length=400, null=True)
    description = models.CharField(max_length=3000, null=True)
    image = models.ImageField(upload_to='polls/questions', blank=True)
    votes = models.IntegerField(default=0, blank=True)
    voted_by = models.ManyToManyField(User, related_name='voted_by', blank=True)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=3)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def get_percent(self):
        percents = round(self.votes * 100 / self.question.votes)
        return percents

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import User


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput)

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password != password2:
            raise ValidationError({
                password2: ValidationError('Пароли не совпадают', code='password_nisnatch')
            })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name', 'username', 'email')


class UpdateForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватарка', required=False)
    first_name = forms.CharField(label='Имя', required=False)
    last_name = forms.CharField(label='Фамилия', required=False)
    username = forms.CharField(label='Логин', required=False)
    email = forms.CharField(label='Почта', required=False)

    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name', 'username', 'email')

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404

from .forms import RegisterForm, UpdateForm
from .models import Question, Choice, User
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth import logout


class Register(generic.CreateView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('polls:login')


class Profile(generic.DetailView):
    model = User
    template_name = 'polls/profile.html'


class DeleteUser(generic.DeleteView):
    model = User
    success_url = reverse_lazy('polls:index')

def logout_view(request):
    logout(request)
    return redirect('polls:index')

class UpdateUser(generic.UpdateView):
    model = User
    form_class = UpdateForm
    success_url = reverse_lazy('polls:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        other_user = User.objects.get(pk=self.kwargs['pk'])
        if self.request.user.pk != other_user.pk:
            raise Http404

        return context


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        quest = Question.objects.get(pk=self.kwargs['pk'])
        if not quest.was_published_recently() and not self.request.user.is_superuser:
            raise Http404

        return context


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Вы не сделали выбор',
        })

    if question.voted_by.filter(id=request.user.id).exists():
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Вы уже приняли участие в голосовании',
        })

    question.voted_by.add(request.user)

    selected_choice.votes += 1
    selected_choice.save()
    question.votes += 1
    question.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Главная {% endblock %}</title>
    <link type="text/css" href="{% static 'polls/css/style.css' %}" rel="stylesheet" />
</head>
<body>
    <div class="header">
        <a class="header__logo" href="{% url 'polls:index' %}">Голосование</a>
        <nav class="header__nav">
            {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <a class="header__avatar" href="{% url 'polls:profile' user.id %}">
                <img class="header__avatar" src="../media/polls/user/admin.png" alt="Аватар пользователя">
            </a>
            {% else %}
            <a class="header__avatar" href="{% url 'polls:profile' user.id %}">
                <img src="{{ user.avatar.url }}" alt="Аватар пользователя">
            </a>
            {% endif %}
            {% endif %}
            {% if user.is_authenticated %}
                <a class="header__button" href="{% url 'polls:profile' user.id %}">Профиль</a>
                <a class="header__button" href="{% url 'polls:logout' %}">Выход</a>
            {% else %}
                <a class="header__button" href="{% url 'polls:login' %}">Вход</a>
                <a class="header__button" href="{% url 'polls:register' %}">Регистрация</a>
            {% endif %}
        </nav>
    </div>
    <main>
        <div>
            {% block content %} {% endblock %}
        </div>
    </main>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %} Вопрос {{ question.question_text }} {% endblock %}

{% block content %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
        <h1>{{question.question_text}}</h1>
        <img class="question__img" src="{{ question.image.url }}" alt="Картинка вопроса">
        <p>Описание: {{ question.description }}</p>
        {% if error_message %}<p><b> {{error_message}}</b></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    <br>
    <input type="submit" value="Vote">
</form>
<br>
<a href="{% url 'polls:results' question.id %}">Посмотреть результаты</a>

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}


{% block content %}

    {% if latest_question_list %}
        <h3>Вопросы:</h3>
            <ul>
            {% for question in latest_question_list %}
                {% if question.was_published_recently or user.is_superuser %}
                    <li>
                        <article>
                            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                            <p>{{ question.short_description }}</p>
                        </article>
                    </li>
                {% endif %}
            {% endfor %}
             </ul>
    {% else %}
        <p>
            Нет вопросов!
        </p>
    {% endif %}

{% endblock %}

polls/templates/polls/profile.html
{% extends 'polls/base.html' %}

{% block title %} Профиль {% endblock %}

{% block content %}

  <div class="profile">
    <h1>Профиль пользователя {{ user.username }}</h1>
    {% if user.is_superuser %}
      <p>Вы администратор данного сайта</p>
    {% else %}
      <img class="profile__avatar" src="{{ user.avatar.url }}" alt="Аватар пользователя">
      <p>Имя: {{ user.first_name }}</p>
      <p>Фамилия: {{ user.last_name }}</p>
      <p>Логин: {{ user.username }}</p>
      <p>Почта: {{ user.email }}</p>
    {% endif %}
      <div class="profile__buttons">
        <a class="profile__button" href="{% url 'polls:delete_user' user.id %}">Удалить профиль</a>
        <a class="profile__button" href="{% url 'polls:update_user' user.id %}">Изменить профиль</a>
      </div>
  </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %} Результаты {% endblock %}

{% block content %}

    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} votes ({% if question.votes > 0 %}{{ choice.get_percent }}%{% endif %})</li>
        {% endfor %}
    </ul>

{% endblock %}

polls/templates/polls/user_confirm_delete.html
{% extends 'polls/base.html' %}


{% block content %}

  <h1>Удаление профиля</h1>
  <p>Вы точно хотите удалить профиль?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Да</button>
  </form>

{% endblock %}

polls/templates/polls/user_form.html
{% extends 'polls/base.html' %}


{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Изменить данные</button>
    </form>

{% endblock %}